trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: app-registration-variables

stages:
  - stage: InstallTerraform
    displayName: 'Install Terraform'
    jobs:
      - job: Install
        steps:
          - script: |
              curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
              sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
              sudo apt-get update && sudo apt-get install terraform -y
              terraform --version
            displayName: 'Install Terraform'

  - stage: PlanTerraform
    displayName: 'Plan Terraform'
    jobs:
      - job: Plan
        steps:
          - script: |
              az login --service-principal -u "$(ARM_CLIENT_ID)" -p "$(ARM_CLIENT_SECRET)" --tenant "$(ARM_TENANT_ID)"
              export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
              export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
              export ARM_TENANT_ID=$(ARM_TENANT_ID)
              export ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)
              terraform init \
                -backend-config="resource_group_name=rg-info-1758_ai" \
                -backend-config="storage_account_name=staistudiohu217832852473" \
                -backend-config="container_name=tfstate" \
                -backend-config="key=tst.terraform.tfstate"
              terraform plan -out=tfplan
            displayName: 'Plan Terraform Changes'

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: 'tfplan' 
              artifact: 'tfplan'
              publishLocation: 'pipeline'
            displayName: 'Publish Terraform Plan Artifact'

  - stage: ApplyTerraform
    displayName: 'Apply Terraform'
    dependsOn: PlanTerraform
    jobs:
      - job: Apply
        steps:
          # Download the tfplan artifact before applying
          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: 'tfplan'
              path: '.'
            displayName: 'Download Terraform Plan Artifact'

          - script: |
              export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
              export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
              export ARM_TENANT_ID=$(ARM_TENANT_ID)
              export ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)
              terraform init \
                -backend-config="resource_group_name=rg-info-1758_ai" \
                -backend-config="storage_account_name=staistudiohu217832852473" \
                -backend-config="container_name=tfstate" \
                -backend-config="key=tst.terraform.tfstate"
              terraform apply -auto-approve tfplan
            displayName: 'Apply Terraform Changes'