name: Terraform Deploy

on:
  push:
    paths:
      - 'environments/dev/**'
      - 'environments/prod/**'
    branches:
      - main

jobs:
  terraform-dev:
    if: contains(github.event.head_commit.modified, 'environments/dev/')
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      TF_BACKEND_RG: rg-info-1758_ai
      TF_BACKEND_STORAGE: staistudiohu217832852473
      TF_BACKEND_CONTAINER: tfstate-terraform
      TF_BACKEND_KEY: dev.terraform.tfstate

    defaults:
      run:
        shell: bash
        working-directory: environments/dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="resource_group_name=$TF_BACKEND_RG" \
            -backend-config="storage_account_name=$TF_BACKEND_STORAGE" \
            -backend-config="container_name=$TF_BACKEND_CONTAINER" \
            -backend-config="key=$TF_BACKEND_KEY"

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve

  terraform-prod:
    if: contains(github.event.head_commit.modified, 'environments/prod/')
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      TF_BACKEND_RG: rg-info-1758_ai
      TF_BACKEND_STORAGE: staistudiohu217832852473
      TF_BACKEND_CONTAINER: tfstate-terraform
      TF_BACKEND_KEY: prod.terraform.tfstate

    defaults:
      run:
        shell: bash
        working-directory: environments/prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="resource_group_name=$TF_BACKEND_RG" \
            -backend-config="storage_account_name=$TF_BACKEND_STORAGE" \
            -backend-config="container_name=$TF_BACKEND_CONTAINER" \
            -backend-config="key=$TF_BACKEND_KEY"

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve